### ISSUE TITLE
随着开发推进，目前比较需要关联查询，和模糊搜索

### ISSUE THREAD

**Issue by vaneoooo** [zhangchunlin/uliweb-apijson#3]
PS:模糊搜索有的：）

随着开发推进，目前比较需要关联查询

**Comment by zhangchunlin** [comment]
fix with https://github.com/zhangchunlin/uliweb-apijson/commit/872eeeb40d214e3075821315ba127be62b2d4413
https://github.com/zhangchunlin/uliweb-apijson/commit/9b5d0e120781342508ea1308a85a18e37b1cefa5
https://github.com/zhangchunlin/uliweb-apijson/commit/d746fb22d27de6e41f1376a93711a34b06319f3c
