### ISSUE TITLE
无法访问，出现500错误

### ISSUE THREAD

**Issue by Kmyu1k** [zhangchunlin/uliweb-apijson#6]
[INFO]  * Loading DebuggedApplication...
[INFO]  * Running on http://localhost:8000/
[INFO]  * Restarting with reloader
[INFO]  * Loading DebuggedApplication...
![image](https://user-images.githubusercontent.com/18068026/80119509-5edb5600-85bc-11ea-99ca-adbb1f66a290.png)

**Comment by zhangchunlin** [comment]
有这种错误,应该有error log的吧,你怎么贴了点前面的log,后面还有吗?

**Comment by Kmyu1k** [comment]
> 有这种错误,应该有error log的吧,你怎么贴了点前面的log,后面还有吗?

没有其他错误了。安装了requirements.txt里面的启动报错，然后我搜索到了你的解决方法
pip uninstall uliweb3
pip install -e git+https://github.com/limodou/uliweb3#egg=uliweb3
换了在demo目录下使用uliweb runserver就发现访问地址出现500错误了，其他的错误信息没有出来
![image](https://user-images.githubusercontent.com/18068026/80176341-d34cde00-862a-11ea-8bdd-ff51169b4071.png)

**Comment by zhangchunlin** [comment]
看你log访问的是 GET /sw.js ,根本没有访问根目录,而且 apijson demo我记得也没有什么 sw.js

**Comment by zhangchunlin** [comment]
我刚测试了一下 pip install -r requirements.txt ,能正常运行 uliweb runserver 这个调试服务器

**Comment by Kmyu1k** [comment]
win10+python3.7,
创建了一个新的虚拟环境后，在uliweb-apijson\demo目录下执行uliweb syncdb报：
> UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 163: illegal multibyte sequence  如图：
![image](https://user-images.githubusercontent.com/18068026/80222746-e1761b00-8679-11ea-92bf-02b531cc2ebf.png)
使用以下命令重新安装uliweb3后在执行uliweb syncdb后可以正常创建表
pip uninstall uliweb3
pip install -e git+https://github.com/limodou/uliweb3#egg=uliweb3
![image](https://user-images.githubusercontent.com/18068026/80223329-b93aec00-867a-11ea-8817-bb585f8a8d67.png)
再执行uliweb dbinit也正常，最后执行uliweb runserver也正常
不知道什么鬼，浏览器换成隐私模式就可以访问了

**Comment by zhangchunlin** [comment]
那个gbk的问题我之前在这里解决的: https://github.com/limodou/uliweb3/commit/7c2265aca25e8f87c1c92b17683dc7c14b263b66
可能还没发包含这个的版本, @limodou 要不发一个 uliweb3的新版本吧

**Comment by zhangchunlin** [comment]
后续有问题也可以来uliweb qq群问: 162487035
